### ISSUE TITLE
Assertion failing in a wrong way

### ISSUE THREAD

**Issue by andreas-zeller** [rindPHI/GrammarGraph#2]
I am getting a `KeyError` in

```
assert grammar[label], f"Grammar has no rules for {label}"
```

This should probably read

```
assert label in grammar, f"Grammar has no rules for {label}"
```

such that `grammar[label]` still evaluates, but the assertion then fails with a message listing the missing label.

**Comment by rindPHI** [comment]
Fixed in 0.1.15.
